# Utilise une image Node.js officielle
FROM node:20

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier package.json et package-lock.json pour installer les dépendances
COPY serveur/package*.json ./

# Installer les dépendances
RUN npm install

# Copier le code source
COPY serveur .

# Exposer le port du serveur
EXPOSE 3000

# Commande pour démarrer le serveur
CMD ["npm", "start"]
