# Utiliser une image Node.js officielle
FROM node:20

# Définir le répertoire de travail
WORKDIR /app

# Copier package.json et installer les dépendances
COPY client/package*.json ./
RUN npm install

# Copier le reste du code source
COPY client .

# Exposer le port 4200 pour le développement
EXPOSE 4200

# Lancer Angular en mode développement avec hot reload
CMD ["npm", "run", "start"]
