### créer un utilisateur
POST http://localhost:3000/register
Content-Type: application/json

{
    "nom":"Dupont",
    "prenom":"jean",
    "email": "jean.dupont@gmail.com",
    "password": "pass2025!",
    "status": "user"
}